### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by ioalim** [ionxeph/suika#7]
Because you made this repo public, i wonder if you accept contributions.
I am not an expert in git stuff at all but i want to try to contribute because I am interested in this Suika game.

**Comment by ionxeph** [comment]
Honestly, I can't tell you honestly I know the proper workflows of public Git repos either. My best recommendation would be fork my repo to a repo of your own, and make any changes you see fit there.

You should be able to make a pull request back to this one from your forked repo.

You should also be able to deploy a version of the game on your own GitHub pages via that forked repo if you'd like.

**Comment by ioalim** [comment]
I think I made a wrong question. 
What I wanted to ask is can I contribute to this repo? And should I directly make a PR to main or develop first? Are there other things i have to keep in mind when contributing?
I have a bit of rust knowledge but it's my first time working with bevy because I usually use [ggez](https://github.com/ggez/ggez/)

**Comment by ionxeph** [comment]
you can open PRs directly to master
